In [1]:
import numpy as np 
import pandas as pd 
import matplotlib.pyplot as plt 
import seaborn as sns

In [2]:
df=pd.read_csv("Churn_Modelling[1].csv")

In [3]:
df.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [4]:
df.shape

(10000, 14)

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   RowNumber        10000 non-null  int64
 1   CustomerId       10000 non-null  int64
 2   Surname          10000 non-null  str
 3   CreditScore      10000 non-null  int64
 4   Geography        10000 non-null  str
 5   Gender           10000 non-null  str
 6   Age              10000 non-null  int64
 7   Tenure           10000 non-null  int64
 8   Balance          10000 non-null  float64
 9   NumOfProducts    10000 non-null  int64
 10  HasCrCard        10000 non-null  int64
 11  IsActiveMember   10000 non-null  int64
 12  EstimatedSalary  10000 non-null  float64
 13  Exited           10000 non-null  int64
dtypes: float64(2), int64(9), str(3)
memory usage: 1.1 MB

In [6]:
df.duplicated().sum()

np.int64(0)

In [7]:
df['Exited'].value_counts()

Exited
0    7963
1    2037
Name: count, dtype: int64

In [8]:
df['Geography'].value_counts()

Geography
France     5014
Germany    2509
Spain      2477
Name: count, dtype: int64

In [9]:
df.drop(columns=['RowNumber','CustomerId','Surname'], inplace=True)

In [10]:
df.head()

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [11]:
pd.get_dummies(df,columns=['Geography','Gender'],drop_first=True)

,CreditScore,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Geography_Germany,Geography_Spain,Gender_Male
0,619,42,2,0.00,1,1,1,101348.88,1,False,False,False
1,608,41,1,83807.86,1,0,1,112542.58,0,False,True,False
2,502,42,8,159660.80,3,1,0,113931.57,1,False,False,False
3,699,39,1,0.00,2,0,0,93826.63,0,False,False,False
4,850,43,2,125510.82,1,1,1,79084.10,0,False,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...
9995,771,39,5,0.00,2,1,0,96270.64,0,False,False,True
9996,516,35,10,57369.61,1,1,1,101699.77,0,False,False,True
9997,709,36,7,0.00,1,0,1,42085.58,1,False,False,False
9998,772,42,3,75075.31,2,1,0,92888.52,1,True,False,True
9999,792,28,4,130142.79,1,1,0,38190.78,0,False,False,False

In [13]:
from sklearn.model_selection import train_test_split

X = pd.get_dummies(
    df.drop(columns=['Exited']),
    columns=['Geography', 'Gender'],
    drop_first=True
)
y = df['Exited']

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=1
)

In [14]:
X

,CreditScore,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Geography_Germany,Geography_Spain,Gender_Male
0,619,42,2,0.00,1,1,1,101348.88,False,False,False
1,608,41,1,83807.86,1,0,1,112542.58,False,True,False
2,502,42,8,159660.80,3,1,0,113931.57,False,False,False
3,699,39,1,0.00,2,0,0,93826.63,False,False,False
4,850,43,2,125510.82,1,1,1,79084.10,False,True,False
...,...,...,...,...,...,...,...,...,...,...,...
9995,771,39,5,0.00,2,1,0,96270.64,False,False,True
9996,516,35,10,57369.61,1,1,1,101699.77,False,False,True
9997,709,36,7,0.00,1,0,1,42085.58,False,False,False
9998,772,42,3,75075.31,2,1,0,92888.52,True,False,True
9999,792,28,4,130142.79,1,1,0,38190.78,False,False,False

In [15]:
from sklearn.preprocessing import StandardScaler
scaler= StandardScaler()

X_train_scaled= scaler.fit_transform(X_train)
X_test_scaled= scaler.transform(X_test)

In [16]:
X_train_scaled

array([[-0.23082038, -0.94449979, -0.70174202, ...,  1.71490137,
        -0.57273139,  0.91509065],
       [-0.25150912, -0.94449979, -0.35520275, ..., -0.58312392,
        -0.57273139, -1.09278791],
       [-0.3963303 ,  0.77498705,  0.33787579, ...,  1.71490137,
        -0.57273139, -1.09278791],
       ...,
       [ 0.22433188,  0.58393295,  1.3774936 , ..., -0.58312392,
        -0.57273139, -1.09278791],
       [ 0.13123255,  0.01077067,  1.03095433, ..., -0.58312392,
        -0.57273139, -1.09278791],
       [ 1.1656695 ,  0.29735181,  0.33787579, ...,  1.71490137,
        -0.57273139,  0.91509065]], shape=(8000, 11))

In [18]:
import tensorflow
from tensorflow import keras
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Dense

In [19]:
model= Sequential()

model.add(Dense(3,activation='sigmoid',input_dim=11))
model.add(Dense(1,activation='sigmoid'))

c:\Users\Asus\AppData\Local\Python\pythoncore-3.12-64\Lib\site-packages\keras\src\layers\core\dense.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [20]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 3)              │            36 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 1)              │             4 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 40 (160.00 B)

 Trainable params: 40 (160.00 B)

 Non-trainable params: 0 (0.00 B)

In [25]:
model.compile(loss='binary_crossentropy',optimizer='adam')

In [36]:
history=model.fit(X_train_scaled,y_train,epochs=200)

Epoch 1/200
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.4028
Epoch 2/200
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.4028
Epoch 3/200
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.4028
Epoch 4/200
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.4028
Epoch 5/200
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.4027
Epoch 6/200
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.4027
Epoch 7/200
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.4028
Epoch 8/200
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.4027
Epoch 9/200
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.4027
Epoch 10/200
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.4027
Epoch 11/200
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.4027
Epoch 12/200
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.4027
Epoch 13/200
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.4027
Epoch 14/200
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.4026
Epoch 15/200
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.4026
Epoch 16/200
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.4027
Epoch 17/200
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.4026
Epoch 18/200
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.4026
Epoch 19/200
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.4026
Epoch 20/200
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.4026
Epoch 21/200
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - loss: 0.4026
Epoch 22/200
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.4026
Epoch 23/200
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.4025
Epoch 24/200
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.4025
Epoch 25/200
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.4026
Epoch 26/200
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.4025
Epoch 27/200
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.4025
Epoch 28/200
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.4025
Epoch 29/200
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.4025
Epoch 30/200
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.4025
Epoch 31/200
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.4024
Epoch 32/200
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.4025
Epoch 33/200
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - loss: 0.4024
Epoch 34/200
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.4025
Epoch 35/200
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.4024
Epoch 36/200
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.4024
Epoch 37/200
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.4023
Epoch 38/200
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.4024
Epoch 39/200
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.4024
Epoch 40/200
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.4024
Epoch 41/200
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.4024
Epoch 42/200
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.4023
Epoch 43/200
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.4023
Epoch 44/200
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.4023
Epoch 45/200
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.4023
Epoch 46/200
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.4023
Epoch 47/200
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.4022
Epoch 48/200
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.4022
Epoch 49/200
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.4023
Epoch 50/200
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.4023
Epoch 51/200
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.4022
Epoch 52/200
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.4022
Epoch 53/200
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.4021
Epoch 54/200
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.4022
Epoch 55/200
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.4021
Epoch 56/200
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.4021
Epoch 57/200
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.4021
Epoch 58/200
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.4021
Epoch 59/200
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.4021
Epoch 60/200
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.4021
Epoch 61/200
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.4020
Epoch 62/200
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.4020
Epoch 63/200
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.4020
Epoch 64/200
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - loss: 0.4020
Epoch 65/200
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.4020
Epoch 66/200
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.4020
Epoch 67/200
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.4020
Epoch 68/200
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.4020
Epoch 69/200
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.4019
Epoch 70/200
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.4019
Epoch 71/200
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.4019
Epoch 72/200
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.4019
Epoch 73/200
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.4018
Epoch 74/200
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.4018
Epoch 75/200
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.4018
Epoch 76/200
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.4018
Epoch 77/200
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.4018
Epoch 78/200
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.4017
Epoch 79/200
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.4017
Epoch 80/200
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.4017
Epoch 81/200
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.4017
Epoch 82/200
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.4017
Epoch 83/200
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.4017
Epoch 84/200
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.4016
Epoch 85/200
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.4016
Epoch 86/200
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.4015
Epoch 87/200
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.4015
Epoch 88/200
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.4016
Epoch 89/200
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.4015
Epoch 90/200
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.4014
Epoch 91/200
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.4014
Epoch 92/200
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.4014
Epoch 93/200
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.4013
Epoch 94/200
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.4014
Epoch 95/200
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.4013
Epoch 96/200
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.4013
Epoch 97/200
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.4013
Epoch 98/200
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.4012
Epoch 99/200
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.4012
Epoch 100/200
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.4012
Epoch 101/200
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.4011
Epoch 102/200
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.4011
Epoch 103/200
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.4011
Epoch 104/200
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - loss: 0.4011
Epoch 105/200
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - loss: 0.4011
Epoch 106/200
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.4010
Epoch 107/200
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.4009
Epoch 108/200
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.4009
Epoch 109/200
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.4009
Epoch 110/200
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.4009
Epoch 111/200
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.4009
Epoch 112/200
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.4007
Epoch 113/200
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.4007
Epoch 114/200
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.4007
Epoch 115/200
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.4007
Epoch 116/200
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - loss: 0.4006
Epoch 117/200
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - loss: 0.4006
Epoch 118/200
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.4005
Epoch 119/200
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.4005
Epoch 120/200
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.4005
Epoch 121/200
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.4004
Epoch 122/200
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.4004
Epoch 123/200
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.4004
Epoch 124/200
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.4003
Epoch 125/200
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.4003
Epoch 126/200
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.4003
Epoch 127/200
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.4002
Epoch 128/200
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.4001
Epoch 129/200
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.4001
Epoch 130/200
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.4000
Epoch 131/200
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.4001
Epoch 132/200
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.4000
Epoch 133/200
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.4000
Epoch 134/200
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.3999
Epoch 135/200
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.3999
Epoch 136/200
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - loss: 0.3999
Epoch 137/200
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.3998
Epoch 138/200
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.3998
Epoch 139/200
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.3997
Epoch 140/200
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.3997
Epoch 141/200
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.3997
Epoch 142/200
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.3996
Epoch 143/200
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.3996
Epoch 144/200
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.3994
Epoch 145/200
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.3995
Epoch 146/200
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.3994
Epoch 147/200
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.3994
Epoch 148/200
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.3993
Epoch 149/200
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - loss: 0.3993
Epoch 150/200
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.3993
Epoch 151/200
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.3991
Epoch 152/200
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.3991
Epoch 153/200
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.3991
Epoch 154/200
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.3991
Epoch 155/200
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.3991
Epoch 156/200
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.3989
Epoch 157/200
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.3989
Epoch 158/200
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.3989
Epoch 159/200
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.3988
Epoch 160/200
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.3988
Epoch 161/200
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.3987
Epoch 162/200
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.3987
Epoch 163/200
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.3986
Epoch 164/200
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.3986
Epoch 165/200
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.3986
Epoch 166/200
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.3985
Epoch 167/200
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.3985
Epoch 168/200
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - loss: 0.3985
Epoch 169/200
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.3984
Epoch 170/200
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.3984
Epoch 171/200
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.3983
Epoch 172/200
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.3983
Epoch 173/200
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.3982
Epoch 174/200
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.3982
Epoch 175/200
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.3982
Epoch 176/200
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - loss: 0.3980
Epoch 177/200
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.3981
Epoch 178/200
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.3980
Epoch 179/200
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.3979
Epoch 180/200
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.3979
Epoch 181/200
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.3979
Epoch 182/200
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.3979
Epoch 183/200
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.3979
Epoch 184/200
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.3978
Epoch 185/200
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.3978
Epoch 186/200
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.3977
Epoch 187/200
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.3976
Epoch 188/200
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.3976
Epoch 189/200
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.3976
Epoch 190/200
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.3975
Epoch 191/200
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.3975
Epoch 192/200
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.3975
Epoch 193/200
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.3974
Epoch 194/200
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.3974
Epoch 195/200
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.3973
Epoch 196/200
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.3974
Epoch 197/200
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.3972
Epoch 198/200
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.3973
Epoch 199/200
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.3972
Epoch 200/200
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.3972

In [37]:
model.layers[0].get_weights()

[array([[ 0.07113212, -0.13212161, -0.30750158],
        [ 0.70667416,  3.0273983 , -3.4197083 ],
        [ 0.08788399,  0.08672167, -0.01770146],
        [-0.17413889, -0.5338107 , -1.4433342 ],
        [-0.16042113, -0.50246227, -0.20097587],
        [ 0.1268026 ,  0.23251435,  0.4089988 ],
        [ 1.3635236 ,  0.98062927, -0.5185045 ],
        [ 0.08861808,  0.04258545, -0.442128  ],
        [-0.15128857,  0.2690154 , -0.8754085 ],
        [ 0.10660522,  0.5015859 ,  0.76678544],
        [ 0.2528703 , -0.01380892,  0.6671014 ]], dtype=float32),
 array([-1.5114357 , -1.1744641 , -0.10779656], dtype=float32)]

In [38]:
y_log=model.predict(X_test_scaled)

63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step

In [39]:
y_pred=np.where(y_log>0.5,1,0)

In [40]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

0.837

In [41]:
history.history

{'loss': [0.40278884768486023,
  0.4027579128742218,
  0.4027845561504364,
  0.4027833342552185,
  0.402709424495697,
  0.4027230739593506,
  0.402753621339798,
  0.40269455313682556,
  0.40272122621536255,
  0.40270596742630005,
  0.402670294046402,
  0.40265554189682007,
  0.4026617109775543,
  0.4026143550872803,
  0.4026046395301819,
  0.4026644825935364,
  0.4025897681713104,
  0.4026001989841461,
  0.4025729298591614,
  0.4025733470916748,
  0.4025868773460388,
  0.4025724232196808,
  0.4025224447250366,
  0.40254661440849304,
  0.4025709927082062,
  0.40253952145576477,
  0.4025256633758545,
  0.40252891182899475,
  0.4025043547153473,
  0.4024869203567505,
  0.40243521332740784,
  0.40245985984802246,
  0.402417927980423,
  0.4024709463119507,
  0.40241554379463196,
  0.4023619592189789,
  0.40231749415397644,
  0.40236300230026245,
  0.40241551399230957,
  0.4024180769920349,
  0.40236696600914,
  0.4023207426071167,
  0.402332067489624,
  0.4023042321205139,
  0.40229612588882446,
  0.4023297429084778,
  0.4022338092327118,
  0.4022327959537506,
  0.4022548198699951,
  0.4022509753704071,
  0.40218132734298706,
  0.40218299627304077,
  0.40211907029151917,
  0.4021701514720917,
  0.4021390676498413,
  0.40208572149276733,
  0.40207159519195557,
  0.4020664095878601,
  0.402057945728302,
  0.40207618474960327,
  0.4020445644855499,
  0.401993989944458,
  0.4019983112812042,
  0.4019906520843506,
  0.4019926190376282,
  0.40199846029281616,
  0.4019722640514374,
  0.4019523561000824,
  0.40190404653549194,
  0.40190836787223816,
  0.4018736779689789,
  0.40187713503837585,
  0.4018416404724121,
  0.401773601770401,
  0.4017931818962097,
  0.4017758071422577,
  0.4018149971961975,
  0.40169525146484375,
  0.4017157554626465,
  0.4017178416252136,
  0.4016773998737335,
  0.4016595184803009,
  0.4016515016555786,
  0.4015646278858185,
  0.4015680253505707,
  0.4015331566333771,
  0.40153124928474426,
  0.40157124400138855,
  0.4014832377433777,
  0.40139302611351013,
  0.40140286087989807,
  0.4013651907444,
  0.4013370871543884,
  0.40136319398880005,
  0.40130314230918884,
  0.4012603759765625,
  0.4013049602508545,
  0.4011813700199127,
  0.4012203514575958,
  0.4011940062046051,
  0.40113162994384766,
  0.40106457471847534,
  0.4010656774044037,
  0.40107935667037964,
  0.4010523855686188,
  0.4010213017463684,
  0.40089869499206543,
  0.40090006589889526,
  0.40085074305534363,
  0.40086036920547485,
  0.4008868932723999,
  0.4007391035556793,
  0.40074604749679565,
  0.4007342457771301,
  0.40069910883903503,
  0.4005930721759796,
  0.40057408809661865,
  0.40053313970565796,
  0.40049487352371216,
  0.4004906117916107,
  0.4004323184490204,
  0.40036314725875854,
  0.4004168212413788,
  0.4003463089466095,
  0.40029022097587585,
  0.40027835965156555,
  0.40022507309913635,
  0.40012654662132263,
  0.40008193254470825,
  0.4000474512577057,
  0.4000963866710663,
  0.3999951481819153,
  0.399991899728775,
  0.3999474048614502,
  0.39985883235931396,
  0.3998545706272125,
  0.3998364508152008,
  0.3997551500797272,
  0.3997257947921753,
  0.39965394139289856,
  0.39965957403182983,
  0.3996185064315796,
  0.3995991051197052,
  0.39944887161254883,
  0.39953282475471497,
  0.39941927790641785,
  0.39935997128486633,
  0.39932629466056824,
  0.39931151270866394,
  0.399297833442688,
  0.3991386592388153,
  0.3990952968597412,
  0.3990977704524994,
  0.3990754783153534,
  0.3990561366081238,
  0.3989242911338806,
  0.3989245593547821,
  0.3988666236400604,
  0.3988463282585144,
  0.3987515866756439,
  0.3987351655960083,
  0.3987438678741455,
  0.3986232280731201,
  0.39860469102859497,
  0.39855143427848816,
  0.3985140919685364,
  0.39845240116119385,
  0.3984680473804474,
  0.3983924388885498,
  0.3983544409275055,
  0.3983094096183777,
  0.3983200490474701,
  0.39816877245903015,
  0.398189514875412,
  0.39816567301750183,
  0.3980095088481903,
  0.39809951186180115,
  0.39802584052085876,
  0.39794251322746277,
  0.3979076147079468,
  0.397856742143631,
  0.3978656530380249,
  0.39786627888679504,
  0.3978131413459778,
  0.39781123399734497,
  0.39767611026763916,
  0.3976373076438904,
  0.39758509397506714,
  0.39759892225265503,
  0.3975103199481964,
  0.3974665403366089,
  0.39746904373168945,
  0.39739474654197693,
  0.3974251449108124,
  0.3972991108894348,
  0.39737552404403687,
  0.39723843336105347,
  0.39726221561431885,
  0.39716559648513794,
  0.39716631174087524]}

In [ ]:
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])
history = model.fit(X_train_scaled, y_train, epochs=200)

plt.plot(history.history['accuracy'])
plt.plot(history.history['loss'])
plt.title('Model accuracy and loss')
plt.ylabel('Value')
plt.xlabel('Epoch')
plt.legend(['Accuracy', 'Loss'])
plt.show()
plt.plot(history.history['loss'])

KeyError: 'accuracy_score'